### ISSUE TITLE
Unable to use QEMU/KVM user session

### ISSUE THREAD

**Issue by NN708** [flathub/org.virt_manager.virt-manager#3]
`virtqemud` is not available in the Flatpak, which prevents the establishment of a connection to the QEMU/KVM user session.

Error message:

```
Unable to connect to libvirt qemu:///session.

binary '/app/bin/virtqemud' does not exist in $PATH: No such file or directory

Libvirt URI is: qemu:///session

Traceback (most recent call last):
  File "/app/share/virt-manager/virtManager/connection.py", line 923, in _do_open
    self._backend.open(cb, data)
  File "/app/share/virt-manager/virtinst/connection.py", line 171, in open
    conn = libvirt.openAuth(self._open_uri,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.12/site-packages/libvirt.py", line 147, in openAuth
    raise libvirtError('virConnectOpenAuth() failed')
libvirt.libvirtError: binary '/app/bin/virtqemud' does not exist in $PATH: No such file or directory
```

**Comment by travier** [comment]
It will not be provided by the flatpak. It should be installed on the host.

**Comment by travier** [comment]
If you want a Flatpak that has everything included then you should look at https://flathub.org/apps/org.gnome.Boxes.

**Comment by travier** [comment]
Hum, we should either disable that option or include everything needed.

**Comment by travier** [comment]
Hum indeed, I have the same behavior. This is weird. I'll look at what GNOME Boxes does.

**Comment by TheRsKing** [comment]
> The initial idea was to keep this a pure client, but it looks like this won't work for the user session part so we would have to include what's needed in the Flatpak.

maybe, if it works as a pure client again, as an extension like alpaca did with the rocm extension https://github.com/flathub/com.jeffser.Alpaca.Plugins.AMD

**Comment by pm4rcin** [comment]
@TheRsKing do you mean the extension that packages the whole qemu or something like that? If yes then that would be great as it would allow to get rid of system packaged qemu since most people don't need the advanced cli options and those that do can always use system packages. But not sure if it's possible to package it like that.

**Comment by TheRsKing** [comment]
> @TheRsKing do you mean the extension that packages the whole qemu or something like that? If yes then that would be great as it would allow to get rid of system packaged qemu since most people don't need the advanced cli options and those that do can always use system packages. But not sure if it's possible to package it like that.

That would be my suggestion, so users who want a pure connection via ssh would have a debloatet virt manager and if you want more you can install the extension / addon with qemu kvm and libvirt. 

I think this is possible. But please note that I am neither a developer nor a significant person behind libvirt, I am a simple experienced linux user with this suggestion ;)

**Comment by RushingAlien** [comment]
Expose --filesystem=xdg-run/libvirt to use user qemu/kvm session @NN708, @travier maybe this permission should be added by default?

**Comment by NN708** [comment]
> Expose `--filesystem=xdg-run/libvirt` to use user qemu/kvm session @NN708, @travier maybe this permission should be added by default?

I can confirm that this works. It would be beneficial to add this to the `finish-args` for user convenience.

The only problem is the lacking of systemd user service for libvirtd, so users need to manually run `virsh --connect qemu:///session list` on the host before launching virt-manager. But this issue falls outside the scope of this repository and is being tracked in [libvirt/libvirt#21](https://gitlab.com/libvirt/libvirt/-/issues/21).

**Comment by travier** [comment]
Thanks for figuring this out! I've made https://github.com/flathub/org.virt_manager.virt-manager/pull/6

**Comment by RushingAlien** [comment]
```
sudo cp /usr/lib/systemd/system/{virt*,libvirt*} /etc/systemd/user/
```
```
sudo sed -i 's|ListenStream=/run/libvirt/\([^[:space:]]*\)|ListenStream=%t/libvirt/\1|g' /etc/systemd/user/{virt*,libvirt*}.socket
```
I simply ran this to get th euser services equivalent.  
then you can `systemctl --user enable --now virtqemud.socket`

**Comment by dnkmmr69420** [comment]
but what if you can't install libvirt on the host system?

**Comment by dnkmmr69420** [comment]
> If you want a Flatpak that has everything included then you should look at https://flathub.org/apps/org.gnome.Boxes.

but it does not have the same features as virt manager

**Comment by tulilirockz** [comment]
Hello everyone! Commented this on the other related issue, but the QEMU extension should work just fine now, could someone test it out a bit and report success/failures? Added instructions in https://github.com/flathub/org.virt_manager.virt-manager/pull/13#issuecomment-2602290347

**Comment by travier** [comment]
Needs https://github.com/flathub/flathub/pull/6005

**Comment by scabala** [comment]
Hi, I have seen latest update of virt-manager flatpak tries to download the Qemu extension. My usecase for virt-manager is only for remote connections. Is there any way to make virt-manager flatpak not install qemu extension by default?

Thanks

**Comment by travier** [comment]
That's what I had asked in https://github.com/flathub/org.virt_manager.virt-manager/pull/13#discussion_r1913065734 but it looks like it was dropped from https://github.com/flathub/org.virt_manager.virt-manager/pull/13 and I missed it. Making a PR.

**Comment by travier** [comment]
https://github.com/flathub/org.virt_manager.virt-manager/pull/21

**Comment by travier** [comment]
This should be resolved as https://github.com/flathub/org.virt_manager.virt_manager.Extension.Qemu is now available.

**Comment by scabala** [comment]
It works, thank you!
